
docker-test:
  # Use the official docker image.
  image: docker/compose:latest
  stage: test
  services:
    - docker:dind

  variables:
    TESTNG_FAILED_XML: jar/test-output/testng-failed.xml
  script:
    - docker-compose up -d --build
    - docker wait test-run
    - chmod +x ./script.sh
    - ./script.sh
    - |
      if [[ -f "$TESTNG_FAILED_XML" ]]; then
        echo "Test failures observed as TestNG-Failed file exists."
        exit 1
      else
        echo "All tests passed Successfully."
      fi

  artifacts:
    reports:
      junit:
        - jar/test-output/junitreports/TEST-*.xml
    paths:
      - output.txt
      - jar/test-output/
      - jar/src/test/resources/results/
    when: always
    expire_in: 1 week

  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
        - docker-compose.yml